
if (typeof levelsData === 'undefined') var levelsData = {};
if (typeof window.levelsData === 'undefined') window.levelsData = {};
window.levelsData = window.levelsData || {};
var levelsData = window.levelsData;

// Audio - use var and avoid duplicate
var audioPart1_08 = (typeof audioPart1_08 !== 'undefined' ? audioPart1_08 : "audio/8/1.mp3");
var audioPart2_08 = (typeof audioPart2_08 !== 'undefined' ? audioPart2_08 : "audio/8/2.mp3");
var audioPart3_08 = (typeof audioPart3_08 !== 'undefined' ? audioPart3_08 : "audio/8/3.mp3");
var audioPart4_08 = (typeof audioPart4_08 !== 'undefined' ? audioPart4_08 : "audio/8/4.mp3");

// If original file had audio/01 etc, override to audio/8 path
audioPart1_08 = "audio/8/1.mp3";
audioPart2_08 = "audio/8/2.mp3";
audioPart3_08 = "audio/8/3.mp3";
audioPart4_08 = audioPart4_08 || "audio/8/4.mp3";

window.levelsData["8"] = {

reading: [
{ tag: "U1_G", qNum: 1, question: "01 Choose the correct sentence order.", options: ["A Do you read a newspaper every day?", "A You do read a newspaper every day?", "A Do you newspaper read a every day?", "A Read you do a newspaper every day?"], correct: 0, exp: "استفهام مضارع بسيط: Do + فاعل + فعل مصدر، عشان نسأل عن عادة يومية." },
    { tag: "U1_G", qNum: 2, question: "02 Choose the correct sentence order.", options: ["A Why are they wearing warm-up suits?", "A Why they are wearing warm-up suits?", "A Are why they wearing warm-up suits?", "A They why are wearing warm-up suits?"], correct: 0, exp: "Why + are + فاعل + V-ing سؤال في المضارع المستمر عن حاجة بتحصل دلوقتي." },
    { tag: "U1_G", qNum: 3, question: "03 Choose the correct sentence order.", options: ["A How many cups of coffee did you drink?", "A How many coffee cups did you drink?", "A Did you drink how many cups of coffee?", "A How many did you drink cups of coffee?"], correct: 0, exp: "How many + اسم جمع + did + فاعل + مصدر، بنسأل عن الكمية اللي شربتها." },
    { tag: "U1_G", qNum: 4, question: "04 Choose the correct sentence order.", options: ["A Can Tony play any musical instruments?", "A Tony can play any musical instruments?", "A Can Tony any musical instruments play?", "A Can any musical instruments Tony play?"], correct: 0, exp: "Can + فاعل + مصدر، سؤال عن القدرة." },
    { tag: "U1_G", qNum: 5, question: "05 Choose the correct sentence order.", options: ["A Which school does Sasha go to?", "A Which school Sasha does go to?", "A Does which school Sasha go to?", "A Which does Sasha go to school?"], correct: 0, exp: "Which school + does + فاعل + مصدر، سؤال عن اختيار." },
    { tag: "U1_G", qNum: 6, question: "06 Choose the correct sentence order.", options: ["A What are you studying in college?", "A What you are studying in college?", "A Are what you studying in college?", "A What studying are you in college?"], correct: 0, exp: "What + are + فاعل + V-ing مضارع مستمر." },
    { tag: "U1_G", qNum: 7, question: "07 My name's Paloma and I live in Manhattan. I go to the movies sometimes, but I ________ the theater. (love)", options: ["A loves", "B love", "C am loving", "D is loving"], correct: 1, exp: "I + love (مضارع بسيط) لأن love فعل شعور مينفعش مستمر، ومع I الفعل من غير s. بنقول I love مش I loves." },
    { tag: "U1_G", qNum: 8, question: "08 What about you? ________ the movies or the theater? (you / prefer)", options: ["A Do you prefer", "B Are you preferring", "C Does you prefer", "D Did you prefer"], correct: 0, exp: "سؤال عن تفضيل عام مضارع بسيط Do you prefer، prefer فعل حالة مينفعش V-ing." },
    { tag: "U1_G", qNum: 9, question: "09 I'm a student, but it's winter vacation, so now I ________ - (not study)", options: ["A don't study", "B 'm not studying", "C not studying", "D am not study"], correct: 1, exp: "now علامة مضارع مستمر مؤقت في الأجازة I'm not studying." },
    { tag: "U1_G", qNum: 10, question: "10 I ________ in a store. (work)", options: ["A work", "B 'm working", "C works", "D working"], correct: 1, exp: "شغل مؤقت في الأجازة مضارع مستمر I'm working." },
    { tag: "U1_G", qNum: 11, question: "11 I ________ some extra money because I'm going to visit Japan next year! (want)", options: ["A wants", "B want", "C am wanting", "D wanting"], correct: 1, exp: "want فعل رغبة مينفعش مستمر ومع I بنقول want." },
    { tag: "U1_G", qNum: 12, question: "12 I ________ Japanese very well, (not speak)", options: ["A don't speak", "B am not speaking", "C doesn't speak", "D not speak"], correct: 0, exp: "حقيقة عامة مضارع بسيط منفي don't speak." },
    { tag: "U1_G", qNum: 13, question: "13 so I ________ some lessons. (take)", options: ["A take", "B 'm taking", "C takes", "D taking"], correct: 1, exp: "بياخد دروس دلوقتي مؤقت مضارع مستمر I'm taking." },
    { tag: "U1_G", qNum: 14, question: "14 ________ any languages at the moment? (you / learn)", options: ["A Do you learn", "B Are you learning", "C Does you learn", "D Did you learn"], correct: 1, exp: "at the moment علامة مضارع مستمر Are you learning." },
    { tag: "U1_G", qNum: 15, question: "15 All of my friends ________ good jobs. (has / have / are have)", options: ["A has", "B have", "C are have", "D is have"], correct: 1, exp: "friends جمع فبنقول have مش has بتاعة المفرد." },
    { tag: "U1_G", qNum: 16, question: "16 We ________ Kerry very well. (don't know / doesn't know / not know)", options: ["A don't know", "B doesn't know", "C not know", "D don't knows"], correct: 0, exp: "We + don't + مصدر، doesn't مع He/She بس." },
    { tag: "U1_G", qNum: 17, question: "17 What time ________ work? (finishes Dave / Dave finishes / does Dave finish)", options: ["A finishes Dave", "B Dave finishes", "C does Dave finish", "D does Dave finishes"], correct: 2, exp: "سؤال مضارع بسيط does + فاعل + مصدر does Dave finish، مينفعش finishes مع does." },
    { tag: "U1_G", qNum: 18, question: "18 Listen! Someone ________ the violin. (playing / is playing / he's playing)", options: ["A playing", "B is playing", "C he's playing", "D are playing"], correct: 1, exp: "Listen! علامة مضارع مستمر حالاً، someone مفرد is playing." },
    { tag: "U1_G", qNum: 19, question: "19 Tom and Kate ________ today. (not working / aren't working / no are working)", options: ["A not working", "B aren't working", "C no are working", "D don't working"], correct: 1, exp: "نفي مستمر aren't working." },
    { tag: "U1_G", qNum: 20, question: "20 Why ________ my computer? (you're using / you using / are you using)", options: ["A you're using", "B you using", "C are you using", "D do you using"], correct: 2, exp: "سؤال مستمر Are + فاعل + V-ing are you using." },
    { tag: "U1_V", qNum: 1, question: "01 Jewelry you wear on your finger. ________", options: ["A a ring", "B a bracelet", "C a cap", "D sandals"], correct: 0, exp: "اللي في الصباع خاتم ring، bracelet في المعصم، cap طاقية." },
    { tag: "U1_V", qNum: 2, question: "02 A jacket and a pair of pants or a skirt. ________", options: ["A a suit", "B a T-shirt", "C gloves", "D boots"], correct: 0, exp: "بدلة كاملة جاكيت وبنطلون suit." },
    { tag: "U1_V", qNum: 3, question: "03 A top you wear in summer. ________", options: ["A a T-shirt", "B a coat", "C a ring", "D tights"], correct: 0, exp: "تيشيرت صيفي T-shirt، coat بالطو شتوي." },
    { tag: "U1_V", qNum: 4, question: "04 You wear them on your hands when it's cold. ________", options: ["A gloves", "B boots", "C sandals", "D a scarf"], correct: 0, exp: "جوانتي للإيد في البرد gloves." },
    { tag: "U1_V", qNum: 5, question: "05 Winter footwear. ________", options: ["A boots", "B sandals", "C a cap", "D a bracelet"], correct: 0, exp: "جزمة شتوي boots، sandals صيفي." },
    { tag: "U1_V", qNum: 6, question: "06 You wear it over your clothes when you go out. ________", options: ["A a coat", "B a suit", "C a ring", "D gloves"], correct: 0, exp: "بالطو فوق الهدوم coat." },
    { tag: "U1_V", qNum: 7, question: "07 There's a big tree ________ of our house. (behind / in front / in the middle)", options: ["A behind", "B in front", "C in the middle", "D on"], correct: 1, exp: "شجرة قدام البيت in front of." },
    { tag: "U1_V", qNum: 8, question: "08 My son has posters ________ the walls of his bedroom. (in / between / on)", options: ["A in", "B on", "C between", "D under"], correct: 1, exp: "بوسترات على الحيطة on the walls." },
    { tag: "U1_V", qNum: 9, question: "09 My desk is the one ________ the window. (between / on the left / near)", options: ["A between", "B near", "C on the left", "D behind"], correct: 1, exp: "قريب من الشباك near." },
    { tag: "U1_V", qNum: 10, question: "10 This is a photo of my family. That's me ________ the middle. (in / on / to)", options: ["A in", "B on", "C to", "D at"], correct: 0, exp: "في النص in the middle." },
    { tag: "U1_V", qNum: 11, question: "11 Who's the man standing ________ you in this photo? (behind / on the right / under)", options: ["A behind", "B on the right", "C under", "D in front"], correct: 0, exp: "واقف وراك behind you." },
    { tag: "U1_V", qNum: 12, question: "12 There's a table ________ my desk and the window. (on / in front / between)", options: ["A between", "B on", "C in front", "D behind"], correct: 0, exp: "بين حاجتين between." },
    { tag: "U1_V", qNum: 13, question: "13 He's ________ height and a little bit overweight. (short / medium / tall)", options: ["A short", "B medium", "C tall", "D overweight"], correct: 1, exp: "متوسط الطول medium height." },
    { tag: "U1_V", qNum: 14, question: "14 Mary never does any work! She's very ________. (generous / hard-working / lazy)", options: ["A generous", "B hard-working", "C lazy", "D friendly"], correct: 2, exp: "مبتعملش شغل كسولة lazy." },
    { tag: "U1_V", qNum: 15, question: "15 Tammy's very ________. She loves meeting new people. (extroverted / hard-working / clever)", options: ["A extroverted", "B hard-working", "C clever", "D quiet"], correct: 0, exp: "بتحب تقابل ناس اجتماعية extroverted." },
    { tag: "U1_V", qNum: 16, question: "16 Antonio is ________ because he doesn't get any exercise. (thin / overweight / slim)", options: ["A thin", "B overweight", "C slim", "D medium"], correct: 1, exp: "وزنه زايد overweight." },
    { tag: "U1_V", qNum: 17, question: "17 My teacher's really ________. She's nice to everybody. (funny / mean / friendly)", options: ["A funny", "B mean", "C friendly", "D bald"], correct: 2, exp: "لطيفة مع الكل friendly." },
    { tag: "U1_V", qNum: 18, question: "18 Jamie doesn't have any hair. He's ________. (fair / bald / blond)", options: ["A fair", "B bald", "C blond", "D long"], correct: 1, exp: "أصلع bald." },
    { tag: "U1_V", qNum: 19, question: "19 Olga has ________ curly hair. (tall / straight / long)", options: ["A tall", "B straight", "C long", "D bald"], correct: 2, exp: "شعر طويل long." },
    { tag: "U1_V", qNum: 20, question: "20 David makes me laugh. He's really ________. (funny / quiet / serious)", options: ["A funny", "B quiet", "C serious", "D lazy"], correct: 0, exp: "مضحك funny." },
    { tag: "U2_G", qNum: 1, question: "01 It ________ when I went to bed. (not snow)", options: ["A wasn't snowing", "B didn't snow", "C wasn't snow", "D not snowing"], correct: 0, exp: "كان مستمر وقت ما رحت أنام ماضي مستمر منفي wasn't snowing." },
    { tag: "U2_G", qNum: 2, question: "02 When ________ her driving test? (she / pass)", options: ["A did she pass", "B was she passing", "C did she passed", "D was she passed"], correct: 0, exp: "حدث منتهي ماضي بسيط did + مصدر did pass." },
    { tag: "U2_G", qNum: 3, question: "03 Donna ________ to the theater with us last night. (not come)", options: ["A didn't come", "B wasn't coming", "C didn't came", "D not came"], correct: 0, exp: "امبارح ماضي بسيط منفي didn't come." },
    { tag: "U2_G", qNum: 4, question: "04 What ________ at six o'clock last night? (you / do)", options: ["A did you do", "B were you doing", "C was you doing", "D did you doing"], correct: 1, exp: "الساعة 6 حاجة كانت شغالة ماضي مستمر were doing." },
    { tag: "U2_G", qNum: 5, question: "05 I ________ when you called. (not study)", options: ["A didn't study", "B wasn't studying", "C wasn't study", "D not studying"], correct: 1, exp: "كنت مش بذاكر وقت المكالمة ماضي مستمر wasn't studying." },
    { tag: "U2_G", qNum: 6, question: "06 Last year they ________ a new house. (buy)", options: ["A bought", "B were buying", "C have bought", "D buyed"], correct: 0, exp: "السنة اللي فاتت ماضي بسيط bought شاذة." },
    { tag: "U2_G", qNum: 7, question: "07 We ________ Rachel at the restaurant yesterday. (see)", options: ["A saw", "B were seeing", "C seen", "D was seeing"], correct: 0, exp: "شفتها امبارح ماضي بسيط saw." },
    { tag: "U2_G", qNum: 8, question: "08 ________ his suit when you saw him? (Dan / wear)", options: ["A Was Dan wearing", "B Did Dan wear", "C Was Dan wear", "D Were Dan wearing"], correct: 0, exp: "كان لابس وقت ما شفته ماضي مستمر Was wearing." },
    { tag: "U2_G", qNum: 9, question: "09 Where ________? (you stay) - In a really nice hotel in Sorrento.", options: ["A did you stay", "B were you staying", "C you stayed", "D did you stayed"], correct: 0, exp: "مكان إقامة في الماضي did you stay." },
    { tag: "U2_G", qNum: 10, question: "10 Who ________ with? (you go) - Sandy and Mel.", options: ["A did you go", "B were you going", "C you went", "D did you went"], correct: 0, exp: "مين رحت معاه did you go." },
    { tag: "U2_G", qNum: 11, question: "11 What ________? (happen) - Mel lost her passport.", options: ["A happened", "B did happen", "C was happening", "D did happened"], correct: 0, exp: "ايه اللي حصل؟ سؤال فاعل happened من غير did." },
    { tag: "U2_G", qNum: 12, question: "12 What ________? (she do) - We went to the police station.", options: ["A did she do", "B was she doing", "C she did", "D did she did"], correct: 0, exp: "هي عملت ايه did she do." },
    { tag: "U2_G", qNum: 13, question: "13 What ________? (they say) - Well - Mel's things were there!", options: ["A did they say", "B were they saying", "C they said", "D did they said"], correct: 0, exp: "قالوا ايه did they say." },
    { tag: "U2_G", qNum: 14, question: "14 Who ________ them? (find) - Two children at the beach.", options: ["A found", "B did find", "C was finding", "D did found"], correct: 0, exp: "مين اللي لقاهم سؤال فاعل found." },
    { tag: "U2_G", qNum: 15, question: "15 Amal doesn't eat meat ________ he's a vegetarian.", options: ["A because", "B although", "C so", "D but"], correct: 0, exp: "سبب because." },
    { tag: "U2_G", qNum: 16, question: "16 ________ the restaurant was expensive, the food was awful.", options: ["A Although", "B Because", "C So", "D But"], correct: 0, exp: "رغم أن Although تناقض." },
    { tag: "U2_G", qNum: 17, question: "17 Tomas doesn't like his job, ________ he's looking for another one.", options: ["A because", "B although", "C so", "D but"], correct: 2, exp: "نتيجة so." },
    { tag: "U2_G", qNum: 18, question: "18 It was a nice day, ________ we went to the beach.", options: ["A because", "B although", "C so", "D but"], correct: 2, exp: "نتيجة so." },
    { tag: "U2_G", qNum: 19, question: "19 They're learning Spanish ________ they want to visit Argentina.", options: ["A because", "B although", "C so", "D but"], correct: 0, exp: "سبب because." },
    { tag: "U2_G", qNum: 20, question: "20 I invited John to the party, ________ he didn't want to come.", options: ["A because", "B although", "C so", "D but"], correct: 3, exp: "تناقض but." },
    { tag: "U2_V", qNum: 1, question: "01 You need to ________ across the road carefully. (meet / run / have)", options: ["A run", "B meet", "C have", "D wait"], correct: 0, exp: "run across the road تعدي الشارع." },
    { tag: "U2_V", qNum: 2, question: "02 We had a great time. We ________ a good time. (have / leave / wait)", options: ["A have", "B leave", "C wait", "D drive"], correct: 0, exp: "have a good time وقت ممتع." },
    { tag: "U2_V", qNum: 3, question: "03 We want to ________ somebody to dinner. (invite / give / eat)", options: ["A invite", "B give", "C eat", "D run"], correct: 0, exp: "تعزم حد invite to dinner." },
    { tag: "U2_V", qNum: 4, question: "04 They ________ along the road slowly. (wait / meet / drive)", options: ["A drive", "B wait", "C meet", "D run"], correct: 0, exp: "يسوقوا على الطريق drive along." },
    { tag: "U2_V", qNum: 5, question: "05 I'm late, I'm ________ in a hurry. (run / be / play)", options: ["A be", "B run", "C play", "D have"], correct: 0, exp: "be in a hurry مستعجل." },
    { tag: "U2_V", qNum: 6, question: "06 Did you ________ for a friend at the station? (wait / run / invite)", options: ["A wait", "B run", "C invite", "D drive"], correct: 0, exp: "wait for a friend تستنى صاحب." },
    { tag: "U2_V", qNum: 7, question: "07 They ________ a song at the party. (take / play / give)", options: ["A play", "B take", "C give", "D have"], correct: 0, exp: "play a song يشغل أغنية." },
    { tag: "U2_V", qNum: 8, question: "08 You need a passport if you want to go ________. (by plane / on vacation / abroad)", options: ["A abroad", "B by plane", "C on vacation", "D delicious"], correct: 0, exp: "تسافر برا abroad." },
    { tag: "U2_V", qNum: 9, question: "09 The food at the restaurant was ________. (comfortable / delicious / crowded)", options: ["A delicious", "B comfortable", "C crowded", "D sunny"], correct: 0, exp: "الأكل لذيذ delicious." },
    { tag: "U2_V", qNum: 10, question: "10 The weather was lovely. It was ________ every day. (foggy / cloudy / sunny)", options: ["A sunny", "B foggy", "C cloudy", "D booked"], correct: 0, exp: "مشمس sunny." },
    { tag: "U2_V", qNum: 11, question: "11 Julie and Andy ________ their flights online. (booked / hired / rented)", options: ["A booked", "B hired", "C rented", "D bought"], correct: 0, exp: "حجزوا طيران booked." },
    { tag: "U2_V", qNum: 12, question: "12 I ________ most of my time at the beach when I'm on vacation. (buy / go / spend)", options: ["A spend", "B buy", "C go", "D take"], correct: 0, exp: "بقضي وقت spend time." },
    { tag: "U2_V", qNum: 13, question: "13 Did you ________ any souvenirs when you were in Brazil? (buy / take / have)", options: ["A buy", "B take", "C have", "D spend"], correct: 0, exp: "تشتري هدايا buy souvenirs." },
    { tag: "U2_V", qNum: 14, question: "14 We went ________ for a few days. (by car / away / out)", options: ["A away", "B by car", "C out", "D abroad"], correct: 0, exp: "سافرنا away." },
    { tag: "U2_V", qNum: 15, question: "15 What did you do ________ the weekend? (at / in / on)", options: ["A on", "B at", "C in", "D for"], correct: 0, exp: "الأمريكي on the weekend." },
    { tag: "U2_V", qNum: 16, question: "16 There was nowhere to sit ________ the train. (at / in / on)", options: ["A on", "B in", "C at", "D for"], correct: 0, exp: "on the train جوه القطر." },
    { tag: "U2_V", qNum: 17, question: "17 They played basketball ________ the morning. (at / in / on)", options: ["A in", "B on", "C at", "D for"], correct: 0, exp: "in the morning." },
    { tag: "U2_V", qNum: 18, question: "18 Stefano was born ________ Rome. (at / in / on)", options: ["A in", "B at", "C on", "D for"], correct: 0, exp: "مدينة كبيرة in Rome." },
    { tag: "U2_V", qNum: 19, question: "19 They sat ________ the balcony. (at / in / on)", options: ["A on", "B in", "C at", "D for"], correct: 0, exp: "on the balcony." },
    { tag: "U2_V", qNum: 20, question: "20 We arrived ________ the bus stop just before the bus left. (at / in / on)", options: ["A at", "B in", "C on", "D for"], correct: 0, exp: "at the bus stop محطة صغيرة." },
    { tag: "U3_G", qNum: 1, question: "01 I / spend / New Year's Eve in San Francisco - Write the sentence.", options: ["A I'm spending New Year's Eve in San Francisco.", "B I spend New Year's Eve in San Francisco.", "C I will spend New Year's Eve in San Francisco.", "D I spending New Year's Eve in San Francisco."], correct: 0, exp: "ترتيب مستقبلي مترتب مضارع مستمر I'm spending." },
    { tag: "U3_G", qNum: 2, question: "02 we / not go / away on New Year's Day - Write the sentence.", options: ["A We aren't going away on New Year's Day.", "B We don't go away on New Year's Day.", "C We not going away on New Year's Day.", "D We aren't go away on New Year's Day."], correct: 0, exp: "نفي مستقبلي We aren't going away." },
    { tag: "U3_G", qNum: 3, question: "03 they / travel / to Toronto on Saturday - Write the sentence.", options: ["A They're travelling to Toronto on Saturday.", "B They travel to Toronto on Saturday.", "C They travelling to Toronto on Saturday.", "D They're travel to Toronto on Saturday."], correct: 0, exp: "They're travelling ترتيب مستقبلي." },
    { tag: "U3_G", qNum: 4, question: "04 when / Simon / get a new car? - Write the question.", options: ["A When is Simon getting a new car?", "B When Simon is getting a new car?", "C When does Simon getting a new car?", "D When is Simon get a new car?"], correct: 0, exp: "When is Simon getting...؟" },
    { tag: "U3_G", qNum: 5, question: "05 I / not have / dinner with Marco tonight - Write the sentence.", options: ["A I'm not having dinner with Marco tonight.", "B I don't have dinner with Marco tonight.", "C I not having dinner with Marco tonight.", "D I'm not have dinner with Marco tonight."], correct: 0, exp: "مش هتعشى مع ماركو الليلة I'm not having." },
    { tag: "U3_G", qNum: 6, question: "06 where / you / meet Tessa? - Write the question.", options: ["A Where are you meeting Tessa?", "B Where you are meeting Tessa?", "C Where do you meeting Tessa?", "D Where are you meet Tessa?"], correct: 0, exp: "Where are you meeting...؟" },
    { tag: "U3_G", qNum: 7, question: "07 \"Cafe\" is a word ________ comes from the Spanish word \"cafeteria\".", options: ["A that", "B where", "C who", "D when"], correct: 0, exp: "كلمة شيء that." },
    { tag: "U3_G", qNum: 8, question: "08 This is the restaurant ________ we had dinner.", options: ["A where", "B that", "C who", "D when"], correct: 0, exp: "مكان where." },
    { tag: "U3_G", qNum: 9, question: "09 Kangaroos are animals ________ live in Australia.", options: ["A that", "B where", "C who", "D when"], correct: 0, exp: "حيوانات that." },
    { tag: "U3_G", qNum: 10, question: "10 A flight attendant is a person ________ looks after passengers on a plane.", options: ["A who / that", "B where", "C that / where", "D who / where"], correct: 0, exp: "شخص who/that." },
    { tag: "U3_G", qNum: 11, question: "11 A snack bar is a place ________ you can get a drink or a meal.", options: ["A where", "B who", "C that", "D when"], correct: 0, exp: "مكان where." },
    { tag: "U3_G", qNum: 12, question: "12 He's the man ________ lives next door to my grandparents.", options: ["A who / that", "B where", "C when", "D which"], correct: 0, exp: "شخص who/that." },
    { tag: "U3_G", qNum: 13, question: "13 One day I ________ around the world. (travel)", options: ["A 'm going to travel", "B going to travel", "C am going travel", "D will going to travel"], correct: 0, exp: "خطة مستقبلية I'm going to travel." },
    { tag: "U3_G", qNum: 14, question: "14 What ________ when you graduate from college? (you / do)", options: ["A are you going to do", "B is you going to do", "C do you going to do", "D are you going do"], correct: 0, exp: "are you going to do؟" },
    { tag: "U3_G", qNum: 15, question: "15 It's very late. We ________ this report today. (not finish)", options: ["A aren't going to finish", "B not going to finish", "C aren't going finish", "D won't going to finish"], correct: 0, exp: "مش هنخلص aren't going to finish." },
    { tag: "U3_G", qNum: 16, question: "16 Do you think Martin ________ his exams? (pass)", options: ["A is going to pass", "B are going to pass", "C going to pass", "D is going pass"], correct: 0, exp: "is going to pass توقع." },
    { tag: "U3_G", qNum: 17, question: "17 Hurry up! We ________ the train. (miss)", options: ["A 're going to miss", "B are going to miss", "C going to miss", "D 're going miss"], correct: 0, exp: "هنفوت القطر we're going to miss." },
    { tag: "U3_G", qNum: 18, question: "18 You don't need an umbrella. It ________. (not rain)", options: ["A isn't going to rain", "B not going to rain", "C isn't going rain", "D not going rain"], correct: 0, exp: "مش هتمطر isn't going to rain." },
    { tag: "U3_G", qNum: 19, question: "19 I don't want to go to the party. I know I ________ it. (not enjoy)", options: ["A 'm not going to enjoy", "B not going to enjoy", "C am not going enjoy", "D won't going to enjoy"], correct: 0, exp: "مش هنبسط I'm not going to enjoy." },
    { tag: "U3_G", qNum: 20, question: "20 How long ________ in Turkey? (Janos and Aisa / be)", options: ["A are Janos and Aisa going to be", "B is Janos and Aisa going to be", "C are Janos and Aisa going be", "D is Janos and Aisa going be"], correct: 0, exp: "are going to be جمع." },
    { tag: "U3_V", qNum: 1, question: "01 Which ________ do international flights leave from? (t______)", options: ["A terminal", "B gate", "C baggage", "D control"], correct: 0, exp: "مبنى terminal." },
    { tag: "U3_V", qNum: 2, question: "02 Flight 460 to Seoul leaves from ________ number 27. (g______)", options: ["A gate", "B terminal", "C cart", "D customs"], correct: 0, exp: "بوابة gate." },
    { tag: "U3_V", qNum: 3, question: "03 After the flight they went to ________ claim to get their suitcases. (b______)", options: ["A baggage", "B control", "C customs", "D elevator"], correct: 0, exp: "baggage claim استلام شنط." },
    { tag: "U3_V", qNum: 4, question: "04 We went through passport ________ before we got on the plane. (c______)", options: ["A control", "B cart", "C customs", "D gate"], correct: 0, exp: "passport control جوازات." },
    { tag: "U3_V", qNum: 5, question: "05 I can't carry all these bags. I need a ________. (c______)", options: ["A cart", "B gate", "C baggage", "D terminal"], correct: 0, exp: "عربية شنط cart." },
    { tag: "U3_V", qNum: 6, question: "06 She didn't stop at ________ as she had nothing to declare. (c______)", options: ["A customs", "B control", "C gate", "D baggage"], correct: 0, exp: "جمارك customs." },
    { tag: "U3_V", qNum: 7, question: "07 You can take the ________ or the stairs to the next floor. (e______)", options: ["A elevator", "B terminal", "C gate", "D cart"], correct: 0, exp: "أسانسير elevator." },
    { tag: "U3_V", qNum: 8, question: "08 Clean is the ________ of dirty.", options: ["A opposite", "B for example", "C kind", "D place"], correct: 0, exp: "عكس opposite." },
    { tag: "U3_V", qNum: 9, question: "09 A dictionary has different uses; ________, you can use it to check pronunciation.", options: ["A for example", "B opposite", "C kind", "D similar"], correct: 0, exp: "مثال for example." },
    { tag: "U3_V", qNum: 10, question: "10 An onion is a ________ of vegetable.", options: ["A kind", "B place", "C something", "D opposite"], correct: 0, exp: "نوع kind." },
    { tag: "U3_V", qNum: 11, question: "11 A market is a ________ where you can buy fresh fruit and vegetables.", options: ["A place", "B opposite", "C kind", "D something"], correct: 0, exp: "مكان place." },
    { tag: "U3_V", qNum: 12, question: "12 A passport is ________ that you need when you travel abroad.", options: ["A something", "B place", "C opposite", "D kind"], correct: 0, exp: "حاجة something." },
    { tag: "U3_V", qNum: 13, question: "13 Fat and overweight have a ________ meaning, but overweight is more polite.", options: ["A similar", "B opposite", "C kind", "D place"], correct: 0, exp: "معنى مشابه similar." },
    { tag: "U3_V", qNum: 14, question: "14 You need to wait ________ a friend at the airport.", options: ["A for", "B in", "C about", "D to"], correct: 0, exp: "wait for." },
    { tag: "U3_V", qNum: 15, question: "15 He fell ________ love with someone on vacation.", options: ["A in", "B for", "C about", "D on"], correct: 0, exp: "fall in love." },
    { tag: "U3_V", qNum: 16, question: "16 She worries ________ a problem at work.", options: ["A about", "B for", "C in", "D on"], correct: 0, exp: "worry about." },
    { tag: "U3_V", qNum: 17, question: "17 I wrote an email ________ somebody yesterday.", options: ["A to", "B for", "C in", "D about"], correct: 0, exp: "write to somebody." },
    { tag: "U3_V", qNum: 18, question: "18 They spend money ________ books every month.", options: ["A on", "B for", "C in", "D about"], correct: 0, exp: "spend on." },
    { tag: "U3_V", qNum: 19, question: "19 Did you pay ________ a meal yesterday?", options: ["A for", "B on", "C about", "D in"], correct: 0, exp: "pay for." },
    { tag: "U3_V", qNum: 20, question: "20 I disagree ________ somebody about politics.", options: ["A with", "B for", "C about", "D on"], correct: 0, exp: "disagree with." },
   ],
listening: {
A: [
   
{ qNum: 1, tag: "P1", partName: "Part 1 - Locations - Where are people? (نموذج A)", audioSrc: audioPart1_08, speaker: "1", startTime: 4, endTime: 25, question: "1. Conversation 1: Where are the people?", options: ["A) at the movies", "B) in class", "C) in a restaurant", "D) on a train"], correct: 0 },
{ qNum: 2, tag: "P1", partName: "Part 1 - Locations - Where are people? (نموذج A)", audioSrc: audioPart1_08, speaker: "2", startTime: 26, endTime: 48, question: "2. Conversation 2: Where are the people?", options: ["A) at home", "B) on a train", "C) in a shop", "D) at work"], correct: 2 },
{ qNum: 3, tag: "P1", partName: "Part 1 - Locations - Where are people? (نموذج A)", audioSrc: audioPart1_08, speaker: "3", startTime: 49, endTime: 74, question: "3. Conversation 3: Where are the people?", options: ["A) in a restaurant", "B) at work", "C) in a shop", "D) on a train"], correct: 3 },
{ qNum: 4, tag: "P1", partName: "Part 1 - Locations - Where are people? (نموذج A)", audioSrc: audioPart1_08, speaker: "4", startTime: 75, endTime: 94, question: "4. Conversation 4: Where are the people?", options: ["A) at home", "B) on a train", "C) at work", "D) in class"], correct: 3 },
{ qNum: 5, tag: "P1", partName: "Part 1 - Locations - Where are people? (نموذج A)", audioSrc: audioPart1_08, speaker: "5", startTime: 95, endTime: 124, question: "5. Conversation 5: Where are the people?", options: ["A) in a restaurant", "B) on a train", "C) at the movies", "D) at work"], correct: 3 },
{ qNum: 6, tag: "P2", partName: "Part 2 - Life Story - Ages (نموذج A)", audioSrc: audioPart2_08, speaker: "6", startTime: 4, endTime: 23, question: "6. At the age of 14, what happened?", options: ["A) she went to Italy with her class at school", "B) she was unhappy because her brother was leaving", "C) she stayed at a luxurious hotel in Paris", "D) she spent her free time on the beach in Australia"], correct: 0 },
{ qNum: 7, tag: "P2", partName: "Part 2 - Life Story - Ages (نموذج A)", audioSrc: audioPart2_08, speaker: "7", startTime: 24, endTime: 45, question: "7. At the age of 15, what happened?", options: ["A) she was unhappy because her brother was leaving", "B) she had a fantastic vacation in Spain with her family", "C) she spent her free time on the beach in Australia", "D) she stayed at a luxurious hotel in Paris"], correct: 1 },
{ qNum: 8, tag: "P2", partName: "Part 2 - Life Story - Ages (نموذج A)", audioSrc: audioPart2_08, speaker: "8", startTime: 46, endTime: 65, question: "8. At the age of 24, what happened?", options: ["A) she was unhappy because her brother was leaving", "B) she went to Italy with her class at school", "C) she spent her free time on the beach in Australia", "D) she stayed at a luxurious hotel in Paris"], correct: 2 },
{ qNum: 9, tag: "P2", partName: "Part 2 - Life Story - Ages (نموذج A)", audioSrc: audioPart2_08, speaker: "9", startTime: 67, endTime: 81, question: "9. At the age of 25, what happened?", options: ["A) she stayed at a luxurious hotel in Paris", "B) she spent her free time on the beach in Australia", "C) she went to Italy with her class at school", "D) she was unhappy because her brother was leaving"], correct: 3 },
{ qNum: 10, tag: "P2", partName: "Part 2 - Life Story - Ages (نموذج A)", audioSrc: audioPart2_08, speaker: "10", startTime: 82, endTime: 102, question: "10. At the age of 28, what happened?", options: ["A) she stayed at a luxurious hotel in Paris", "B) she had a fantastic vacation in Spain with her family", "C) she went to Italy with her class at school", "D) she spent her free time on the beach in Australia"], correct: 0 },
{ qNum: 11, tag: "P3", partName: "Part 3 - Plans - What are they planning? (نموذج A)", audioSrc: audioPart3_08, speaker: "11", startTime: 4, endTime: 18, question: "11. Conversation 1: What are they planning to do?", options: ["A) to go to a conference", "B) to cook dinner", "C) to teach English", "D) to go to the airport"], correct: 3 },
{ qNum: 12, tag: "P3", partName: "Part 3 - Plans - What are they planning? (نموذج A)", audioSrc: audioPart3_08, speaker: "12", startTime: 19, endTime: 34, question: "12. Conversation 2: What are they planning to do?", options: ["A) to cook dinner", "B) to go biking", "C) to go to a conference", "D) to go to the airport"], correct: 2 },
{ qNum: 13, tag: "P3", partName: "Part 3 - Plans - What are they planning? (نموذج A)", audioSrc: audioPart3_08, speaker: "13", startTime: 35, endTime: 49, question: "13. Conversation 3: What are they planning to do?", options: ["A) to go to the airport", "B) to teach English", "C) to go biking", "D) to cook dinner"], correct: 1 },
{ qNum: 14, tag: "P3", partName: "Part 3 - Plans - What are they planning? (نموذج A)", audioSrc: audioPart3_08, speaker: "14", startTime: 50, endTime: 70, question: "14. Conversation 4: What are they planning to do?", options: ["A) to teach English", "B) to go biking", "C) to go to the airport", "D) to cook dinner"], correct: 1 },
{ qNum: 15, tag: "P3", partName: "Part 3 - Plans - What are they planning? (نموذج A)", audioSrc: audioPart3_08, speaker: "15", startTime: 71, endTime: 89, question: "15. Conversation 5: What are they planning to do?", options: ["A) to go biking", "B) to go to a conference", "C) to cook dinner", "D) to go to the airport"], correct: 2 },],


}};


// Compatibility for both "8" and "08"
window.levelsData["08"] = window.levelsData["8"];
levelsData["8"] = window.levelsData["8"];
levelsData["08"] = window.levelsData["8"];

