

if (typeof levelsData === 'undefined') var levelsData = {};
const audioPart1_5 = "audio/5/1.mp3";
const audioPart2_5= "audio/5/2.mp3";
const audioPart3_5= "audio/5/3.mp3";

if (typeof levelsData === "undefined") var levelsData = {};
levelsData["5"] = {
reading: [
 

{"tag":"U4_G","qNum":1,"question":"1 Which sentence is correct?","options":["A We hardly watch ever TV.","B We hardly ever watch TV.","C We watch hardly ever TV.","D We ever hardly watch TV."],"correct":1,"exp":"hardly ever يأتي قبل الفعل الرئيسي."},
{"tag":"U4_G","qNum":2,"question":"2 Which sentence is correct?","options":["A They two or three times a week eat pasta.","B They eat pasta two or three times a week.","C They eat two or three times a week pasta.","D They eat pasta a week two or three times."],"correct":1,"exp":"ظرف التكرار two or three times a week يأتي في نهاية الجملة."},
{"tag":"U4_G","qNum":3,"question":"3 Which sentence is correct?","options":["A He's always late for lessons.","B He always is late for lessons.","C Always he's late for lessons.","D He's late always for lessons."],"correct":0,"exp":"always مع فعل be يأتي بعده مباشرة: be + always + late."},
{"tag":"U4_G","qNum":4,"question":"4 Which sentence is correct?","options":["A I don't eat often chocolate.","B I don't often eat chocolate.","C I often don't eat chocolate.","D I don't often chocolate eat."],"correct":1,"exp":"often يأتي قبل الفعل الرئيسي eat وليس بعده."},
{"tag":"U4_G","qNum":5,"question":"5 Which sentence is correct?","options":["A Amy every week plays tennis with her friends.","B Amy plays every week tennis with her friends.","C Amy plays tennis with her friends every week.","D Amy plays tennis every week with her friends friends."],"correct":2,"exp":"every week في نهاية الجملة هو الترتيب الطبيعي."},
{"tag":"U4_G","qNum":6,"question":"6 Which sentence is correct?","options":["A Are you tired in the morning often?","B Are you often tired in the morning?","C Are you tired often in the morning?","D Often are you tired in the morning?"],"correct":1,"exp":"often يأتي بعد فعل be في السؤال."},
{"tag":"U4_G","qNum":7,"question":"7 Which sentence is correct?","options":["A Never I have breakfast.","B I never have breakfast.","C I have never breakfast.","D I have breakfast never."],"correct":1,"exp":"never يأتي قبل الفعل الرئيسي في الجملة المثبتة."},
{"tag":"U4_G","qNum":8,"question":"8 Do you usually have lunch ___ school?","options":["A at","B in","C on","D to"],"correct":0,"exp":"have lunch at school تعبير ثابت بحرف at."},
{"tag":"U4_G","qNum":9,"question":"9 It's very cold ___ December.","options":["A at","B in","C on","D to"],"correct":1,"exp":"نستخدم in مع الأشهر."},
{"tag":"U4_G","qNum":10,"question":"10 The party is ___ Friday.","options":["A at","B in","C on","D to"],"correct":2,"exp":"نستخدم on مع أيام الأسبوع."},
{"tag":"U4_G","qNum":11,"question":"11 I have French classes ___ the evening.","options":["A at","B in","C on","D to"],"correct":1,"exp":"in the evening هو التعبير الصحيح."},
{"tag":"U4_G","qNum":12,"question":"12 We go ___ the city centre by bus.","options":["A at","B in","C on","D to"],"correct":3,"exp":"go to مكان للاتجاه."},
{"tag":"U4_G","qNum":13,"question":"13 I often go to the cinema ___ the weekend.","options":["A at","B in","C on","D to"],"correct":2,"exp":"في الإنجليزية الأمريكية نقول on the weekend."},
{"tag":"U4_G","qNum":14,"question":"14 Barbara works ___ an office.","options":["A at","B in","C on","D to"],"correct":1,"exp":"work in an office للعمل داخل مكان."},
{"tag":"U4_G","qNum":15,"question":"15 This is my ___ wife.","options":["A brothers'","B brother's","C brothers","D brother"],"correct":1,"exp":"المفرد brother نضيف 's للملكية."},
{"tag":"U4_G","qNum":16,"question":"16 I like James but I don't like ___ brother.","options":["A Jame's","B James's","C James'","D Jameses"],"correct":1,"exp":"الأسماء المنتهية بـ s نضيف 's أيضاً: James's."},
{"tag":"U4_G","qNum":17,"question":"17 ___ dictionary is this?","options":["A Who's","B Whose","C Whos'","D Whose's"],"correct":1,"exp":"Whose للسؤال عن الملكية، Who's = who is."},
{"tag":"U4_G","qNum":18,"question":"18 It's ___ pen.","options":["A the Tim's","B Tim's","C Tims'","D Tims"],"correct":1,"exp":"لا نستخدم the مع اسم الملكية، فقط Tim's."},
{"tag":"U4_G","qNum":19,"question":"19 These are my ___ books.","options":["A childrens'","B children's","C childrens","D childrens's"],"correct":1,"exp":"children جمع شاذ، ملكيته children's."},
{"tag":"U4_G","qNum":20,"question":"20 That's my ___ car.","options":["A parents","B parents'","C parent's","D parents's"],"correct":1,"exp":"parents جمع، ملكيته بإضافة ' فقط: parents'."},
{"tag":"U4_V","qNum":1,"question":"1 James is David's ___. Family tree: Mark=Jane, Sally=Paul, Robert=Linda, John David Mary Sam Carla","options":["A uncle","B aunt","C brother","D cousin"],"correct":0,"exp":"James أخو والد David إذن هو uncle حسب شجرة العائلة."},
{"tag":"U4_V","qNum":2,"question":"2 Mary is Carla's ___.","options":["A sister","B cousin","C niece","D daughter"],"correct":1,"exp":"Mary و Carla بنات عم، إذن cousins."},
{"tag":"U4_V","qNum":3,"question":"3 Jane is Sam's ___.","options":["A mother","B grandmother","C aunt","D sister"],"correct":1,"exp":"Jane جدة Sam في الشجرة، إذن grandmother."},
{"tag":"U4_V","qNum":4,"question":"4 Mary is Robert's ___.","options":["A daughter","B niece","C grandson","D wife"],"correct":1,"exp":"Mary ابنة أخ/أخت Robert إذن هي niece."},
{"tag":"U4_V","qNum":5,"question":"5 Sally is Mark's ___.","options":["A niece","B daughter","C granddaughter","D cousin"],"correct":1,"exp":"Sally ابنة Mark و Jane إذن daughter."},
{"tag":"U4_V","qNum":6,"question":"6 Paul is David's ___.","options":["A brother","B father","C uncle","D grandfather"],"correct":1,"exp":"Paul والد David في الشجرة."},
{"tag":"U4_V","qNum":7,"question":"7 David is Mark's ___.","options":["A grandson","B son","C nephew","D cousin"],"correct":0,"exp":"David حفيد Mark، إذن grandson."},
{"tag":"U4_V","qNum":8,"question":"8 I ___ a bath every morning.","options":["A have","B has","C having","D had"],"correct":0,"exp":"have a bath تعبير روتين يومي مع I."},
{"tag":"U4_V","qNum":9,"question":"9 We ___ to school by car.","options":["A goes","B go","C going","D went"],"correct":1,"exp":"We مع المضارع البسيط تأخذ go بدون s."},
{"tag":"U4_V","qNum":10,"question":"10 She ___ school at half past three.","options":["A finishes","B finish","C finishing","D finished"],"correct":0,"exp":"She مفردة إذن finishes بإضافة es."},
{"tag":"U4_V","qNum":11,"question":"11 He ___ breakfast every morning.","options":["A have","B has","C having","D had"],"correct":1,"exp":"He has breakfast هو التعبير الصحيح."},
{"tag":"U4_V","qNum":12,"question":"12 We ___ the dog for a walk twice a day.","options":["A take","B takes","C taking","D took"],"correct":0,"exp":"take the dog for a walk تعبير ثابت."},
{"tag":"U4_V","qNum":13,"question":"13 They ___ shopping at the weekend.","options":["A goes","B go","C going","D went"],"correct":1,"exp":"go shopping تعبير ثابت مع They."},
{"tag":"U4_V","qNum":14,"question":"14 I usually ___ in the evenings after work.","options":["A relax","B relaxes","C relaxing","D relaxed"],"correct":0,"exp":"usually مع المضارع البسيط: I relax."},
{"tag":"U4_V","qNum":15,"question":"15 I work from 9 a.m. to 3 p.m. That's six ___ a day.","options":["A seconds","B hours","C days","D weeks"],"correct":1,"exp":"من 9 إلى 3 هي ست ساعات hours."},
{"tag":"U4_V","qNum":16,"question":"16 John hardly ___ washes his car.","options":["A never","B ever","C always","D usually"],"correct":1,"exp":"hardly ever تعبير ثابت يعني نادراً."},
{"tag":"U4_V","qNum":17,"question":"17 They have English classes ___ a week.","options":["A twice","B three times","C four times","D once"],"correct":1,"exp":"حسب النص الأصلي الإجابة three times a week."},
{"tag":"U4_V","qNum":18,"question":"18 I ___ start work at 8 a.m., but on Mondays I start at 9 a.m.","options":["A always","B usually","C never","D ever"],"correct":1,"exp":"usually للعادة مع استثناء يوم الاثنين."},
{"tag":"U4_V","qNum":19,"question":"19 We don't work every ___. On Saturday and Sunday we relax.","options":["A day","B week","C month","D year"],"correct":0,"exp":"every day كل يوم، منطقي مع عطلة نهاية الأسبوع."},
{"tag":"U4_V","qNum":20,"question":"20 How many ___ are there in a year? Fifty-two.","options":["A weeks","B months","C days","D hours"],"correct":0,"exp":"السنة فيها 52 weeks."},
{"tag":"U5_G","qNum":1,"question":"1 What is the correct order?","options":["A What do you do at the moment?","B What are you doing at the moment?","C What you are doing at the moment?","D What are you do at the moment?"],"correct":1,"exp":"السؤال عن اللحظة الحالية يتطلب are you doing."},
{"tag":"U5_G","qNum":2,"question":"2 Choose the correct sentence.","options":["A We run because it's late.","B We're running because it's late.","C We are run because it's late.","D We running because it's late."],"correct":1,"exp":"we're running صيغة المضارع المستمر مع contraction."},
{"tag":"U5_G","qNum":3,"question":"3 What is the correct order?","options":["A Why Dave and his wife are arguing?","B Why are Dave and his wife arguing?","C Why do Dave and his wife argue?","D Why is Dave and his wife arguing?"],"correct":1,"exp":"ترتيب السؤال: Why are + فاعل جمع + arguing?"},
{"tag":"U5_G","qNum":4,"question":"4 Choose the correct sentence.","options":["A They don't wait for a taxi.","B They aren't waiting for a taxi.","C They not waiting for a taxi.","D They aren't wait for a taxi."],"correct":1,"exp":"النفي في المستمر: aren't waiting."},
{"tag":"U5_G","qNum":5,"question":"5 What is the correct order?","options":["A Do you use this computer?","B Are you using this computer?","C You are using this computer?","D Are you use this computer?"],"correct":1,"exp":"سؤال عن استخدام الحاسوب الآن: Are you using...?"},
{"tag":"U5_G","qNum":6,"question":"6 What is the correct order?","options":["A Does Paul get dressed?","B Is Paul getting dressed?","C Is Paul get dressed?","D Does Paul getting dressed?"],"correct":1,"exp":"Is Paul getting dressed? سؤال مستمر."},
{"tag":"U5_G","qNum":7,"question":"7 Choose the correct sentence.","options":["A I don't wear a jacket today.","B I'm not wearing a jacket today.","C I not wearing a jacket today.","D I'm not wear a jacket today."],"correct":1,"exp":"اليوم الآن: I'm not wearing."},
{"tag":"U5_G","qNum":8,"question":"8 I'm sitting on my bed and I ___ a computer game.","options":["A play","B 'm playing","C playing","D plays"],"correct":1,"exp":"play الآن إذن مضارع مستمر: 'm playing."},
{"tag":"U5_G","qNum":9,"question":"9 I usually ___ in the evenings.","options":["A study","B studying","C am studying","D studies"],"correct":0,"exp":"usually تدل على عادة = مضارع بسيط study."},
{"tag":"U5_G","qNum":10,"question":"10 I ___ out with my friends.","options":["A go","B goes","C going","D am going"],"correct":0,"exp":"عادة: I go مع usually الضمنية."},
{"tag":"U5_G","qNum":11,"question":"11 Mom ___ dinner.","options":["A makes","B 's making","C make","D making"],"correct":1,"exp":"الآن في المطبخ: is making = 's making."},
{"tag":"U5_G","qNum":12,"question":"12 I ___ Dad ___ Julie.","options":["A think","B am thinking","C thinks","D thinking"],"correct":0,"exp":"think كفعل رأي يستخدم بسيط وليس مستمر."},
{"tag":"U5_G","qNum":13,"question":"13 Dad ___ Julie with her homework.","options":["A helps","B 's helping","C help","D helping"],"correct":1,"exp":"فعل يحدث الآن: 's helping / is helping."},
{"tag":"U5_G","qNum":14,"question":"14 Mom ___ me to help her in the kitchen.","options":["A want","B wants","C is wanting","D wanting"],"correct":1,"exp":"want فعل حالة يأتي بسيط: wants."},
{"tag":"U5_G","qNum":15,"question":"15 ___ you come to the movies tonight?","options":["A Do you can","B Can you","C You can","D Can you to"],"correct":1,"exp":"Can يأتي قبل الفاعل في السؤال."},
{"tag":"U5_G","qNum":16,"question":"16 She ___ cook very well.","options":["A no cannot","B can't","C cannot no","D can not no"],"correct":1,"exp":"النفي الصحيح: can't."},
{"tag":"U5_G","qNum":17,"question":"17 'Can you play tennis?' 'Yes, I ___.'","options":["A can play","B can","C can't","D can to"],"correct":1,"exp":"الإجابة القصيرة: Yes, I can."},
{"tag":"U5_G","qNum":18,"question":"18 ___ do the exercises?","options":["A They can","B Can they","C Can they to","D They can to"],"correct":1,"exp":"سؤال بـ Can: Can they...?"},
{"tag":"U5_G","qNum":19,"question":"19 He ___ Italian.","options":["A can't speak","B speaks","C can speak","D speak"],"correct":0,"exp":"حسب المفتاح: can't speak هو النفي الصحيح."},
{"tag":"U5_G","qNum":20,"question":"20 Can you ___ the piano?","options":["A play","B to play","C playing","D plays"],"correct":0,"exp":"بعد can يأتي فعل مجرد: play."},
{"tag":"U5_V","qNum":1,"question":"1 Can you ___ me with this question?","options":["A help","B talk","C tell","D speak"],"correct":0,"exp":"help me with تعبير للمساعدة."},
{"tag":"U5_V","qNum":2,"question":"2 Don't move! I want to ___ your photo.","options":["A draw","B take","C paint","D make"],"correct":1,"exp":"take your photo هو التعبير الصحيح."},
{"tag":"U5_V","qNum":3,"question":"3 It's cold but some people are ___ in the sea.","options":["A waiting","B driving","C swimming","D running"],"correct":2,"exp":"swimming in the sea السباحة في البحر."},
{"tag":"U5_V","qNum":4,"question":"4 Ellen can't ___ her purse.","options":["A find","B watch","C look","D see"],"correct":0,"exp":"can't find لا تستطيع إيجاد."},
{"tag":"U5_V","qNum":5,"question":"5 Let's ___ for a coffee after the class.","options":["A wait","B do","C meet","D go"],"correct":2,"exp":"meet for a coffee للقاء."},
{"tag":"U5_V","qNum":6,"question":"6 I usually ___ my children a story before they go to sleep.","options":["A tell","B play","C remember","D say"],"correct":0,"exp":"tell a story يروي قصة."},
{"tag":"U5_V","qNum":7,"question":"7 He ___ to the gym on the weekend.","options":["A rides","B goes","C plays","D does"],"correct":1,"exp":"goes to the gym يذهب للصالة."},
{"tag":"U5_V","qNum":8,"question":"8 Can you ___ a noise downstairs?","options":["A listen","B take","C hear","D look"],"correct":2,"exp":"hear a noise يسمع ضوضاء، listen يحتاج to."},
{"tag":"U5_V","qNum":9,"question":"9 I can't see very well because it's f___.","options":["A foggy","B hot","C warm","D cloudy"],"correct":0,"exp":"foggy ضبابي يمنع الرؤية."},
{"tag":"U5_V","qNum":10,"question":"10 It's ___ in here. Can you open the window?","options":["A hot","B cold","C foggy","D rainy"],"correct":0,"exp":"hot حار يحتاج فتح النافذة."},
{"tag":"U5_V","qNum":11,"question":"11 The sun's ___. It's a lovely day.","options":["A shining","B raining","C snowing","D cloudy"],"correct":0,"exp":"The sun's shining الشمس مشرقة."},
{"tag":"U5_V","qNum":12,"question":"12 It's ___. Do you have an umbrella?","options":["A raining","B shining","C warm","D foggy"],"correct":0,"exp":"raining ممطر يحتاج مظلة."},
{"tag":"U5_V","qNum":13,"question":"13 Let's go to the park. It's a nice ___ day.","options":["A warm","B hot","C cold","D foggy"],"correct":0,"exp":"warm day يوم دافئ مناسب للحديقة."},
{"tag":"U5_V","qNum":14,"question":"14 You can't see the sun when it's ___.","options":["A cloudy","B sunny","C warm","D hot"],"correct":0,"exp":"cloudy غائم يحجب الشمس."},
{"tag":"U5_V","qNum":15,"question":"15 ___ loud music","options":["A play","B make","C dance","D see"],"correct":0,"exp":"play loud music يشغل موسيقى عالية."},
{"tag":"U5_V","qNum":16,"question":"16 ___ a noise","options":["A play","B make","C turn on","D dance"],"correct":1,"exp":"make a noise يحدث ضوضاء."},
{"tag":"U5_V","qNum":17,"question":"17 ___ the washing machine","options":["A turn on","B play","C dance","D make"],"correct":0,"exp":"turn on the washing machine يشغل الغسالة."},
{"tag":"U5_V","qNum":18,"question":"18 ___ the tango","options":["A dance","B play","C make","D see"],"correct":0,"exp":"dance the tango يرقص التانجو."},
{"tag":"U5_V","qNum":19,"question":"19 ___ somebody's name","options":["A forget","B play","C make","D turn on"],"correct":0,"exp":"forget somebody's name ينسى اسم شخص."},
{"tag":"U5_V","qNum":20,"question":"20 ___ a movie at the theater","options":["A see","B play","C dance","D make"],"correct":0,"exp":"see a movie يشاهد فيلماً."},
{"tag":"U6_G","qNum":1,"question":"1 What ___ they listening to?","options":["A do","B are","C is","D does"],"correct":1,"exp":"What are they listening to? جمع مع are."},
{"tag":"U6_G","qNum":2,"question":"2 Jill ___ at school today.","options":["A doesn't","B isn't","C don't","D aren't"],"correct":1,"exp":"Jill مفرد مع be: isn't at school."},
{"tag":"U6_G","qNum":3,"question":"3 The students ___ like taking tests.","options":["A don't","B aren't","C doesn't","D isn't"],"correct":0,"exp":"students جمع مع do: don't like."},
{"tag":"U6_G","qNum":4,"question":"4 ___ this Sam's cell phone?","options":["A Does","B Is","C Do","D Are"],"correct":1,"exp":"سؤال عن ملكية به is: Is this...?"},
{"tag":"U6_G","qNum":5,"question":"5 ___ you like swimming?","options":["A Do","B Are","C Does","D Is"],"correct":0,"exp":"like فعل عادي يحتاج Do في السؤال."},
{"tag":"U6_G","qNum":6,"question":"6 Where ___ he from?","options":["A does","B is","C do","D are"],"correct":1,"exp":"Where is he from? سؤال عن الأصل بـ be."},
{"tag":"U6_G","qNum":7,"question":"7 I don't like studying, but I like ___ a student.","options":["A be","B being","C to be","D been"],"correct":1,"exp":"like يتبعه -ing: being."},
{"tag":"U6_G","qNum":8,"question":"8 We like ___ in the student center and talking.","options":["A sit","B sitting","C to sit","D sits"],"correct":1,"exp":"like + sitting."},
{"tag":"U6_G","qNum":9,"question":"9 We also like ___ good music.","options":["A listen","B listening","C to listening","D listens"],"correct":1,"exp":"like listening to music."},
{"tag":"U6_G","qNum":10,"question":"10 We both hate ___.","options":["A dance","B dancing","C to dance","D dances"],"correct":1,"exp":"hate dancing يكره الرقص."},
{"tag":"U6_G","qNum":11,"question":"11 I love ___ home on the weekend.","options":["A go","B going","C to go","D goes"],"correct":1,"exp":"love going home يحب الذهاب للبيت."},
{"tag":"U6_G","qNum":12,"question":"12 What do you like ___?","options":["A do","B doing","C to do","D does"],"correct":1,"exp":"What do you like doing? ماذا تحب أن تفعل."},
{"tag":"U6_G","qNum":13,"question":"13 Are they German? Can you ask ___?","options":["A them","B they","C their","D theirs"],"correct":0,"exp":"ask them ضمير مفعول."},
{"tag":"U6_G","qNum":14,"question":"14 He likes Maria, but he doesn't love ___.","options":["A she","B her","C hers","D herself"],"correct":1,"exp":"love her ضمير مفعول."},
{"tag":"U6_G","qNum":15,"question":"15 We don't speak Japanese. They can't understand ___.","options":["A we","B us","C our","D ours"],"correct":1,"exp":"understand us يفهمنا."},
{"tag":"U6_G","qNum":16,"question":"16 Can you help ___? I can't do my homework.","options":["A I","B me","C my","D mine"],"correct":1,"exp":"help me ساعدني."},
{"tag":"U6_G","qNum":17,"question":"17 It isn't ___ car. He has a red car.","options":["A his","B him","C he","D himself"],"correct":0,"exp":"his car صفة ملكية قبل الاسم."},
{"tag":"U6_G","qNum":18,"question":"18 That isn't ___ house. They don't live on this street.","options":["A their","B them","C they","D theirs"],"correct":0,"exp":"their house صفة ملكية للجمع."},
{"tag":"U6_G","qNum":19,"question":"19 We're friends. You like me and I like ___.","options":["A you","B your","C yours","D yourself"],"correct":0,"exp":"I like you أنا أحبك."},
{"tag":"U6_G","qNum":20,"question":"20 It isn't a good movie. I don't like ___.","options":["A it","B its","C it's","D itself"],"correct":0,"exp":"don't like it لا أحبه."},
{"tag":"U6_V","qNum":1,"question":"1 nineteenth, twentieth, ___.","options":["A twenty-first","B twenty-one","C twentieth-one","D twenty-oneth"],"correct":0,"exp":"الترتيب بعد twentieth هو twenty-first."},
{"tag":"U6_V","qNum":2,"question":"2 May, ___, July","options":["A June","B August","C April","D September"],"correct":0,"exp":"ترتيب الشهور: May, June, July."},
{"tag":"U6_V","qNum":3,"question":"3 spring, summer, ___, winter","options":["A fall","B spring","C summer","D winter"],"correct":0,"exp":"في الأمريكية fall هو الخريف بين summer و winter."},
{"tag":"U6_V","qNum":4,"question":"4 seventh, eighth, ninth, ___","options":["A tenth","B ten","C tenthth","D nineth"],"correct":0,"exp":"بعد ninth يأتي tenth."},
{"tag":"U6_V","qNum":5,"question":"5 November, December, ___","options":["A January","B February","C March","D October"],"correct":0,"exp":"بعد December يأتي January من السنة الجديدة."},
{"tag":"U6_V","qNum":6,"question":"6 second, third, fourth, ___","options":["A fifth","B fiveth","C five","D four"],"correct":0,"exp":"fourth بعده fifth."},
{"tag":"U6_V","qNum":7,"question":"7 ___, March, April","options":["A February","B January","C May","D June"],"correct":0,"exp":"قبل March هو February."},
{"tag":"U6_V","qNum":8,"question":"8 fortyfifth, ___, fortyseventh","options":["A fortysixth","B forty-six","C forty-sixth","D fortysix"],"correct":0,"exp":"بين fortyfifth و fortyseventh هو fortysixth."},
{"tag":"U6_V","qNum":9,"question":"9 I'm a receptionist. I greet visitors and ___ the phone.","options":["A answer","B call","C press","D ring"],"correct":0,"exp":"answer the phone يرد على الهاتف."},
{"tag":"U6_V","qNum":10,"question":"10 Oh, that's my phone. It's ___.","options":["A ringing","B answering","C calling","D pressing"],"correct":0,"exp":"ringing يرن."},
{"tag":"U6_V","qNum":11,"question":"11 You have the ___ number.","options":["A wrong","B right","C correct","D message"],"correct":0,"exp":"wrong number الرقم الخطأ."},
{"tag":"U6_V","qNum":12,"question":"12 Can you give her a ___?","options":["A message","B call","C answer","D press"],"correct":0,"exp":"give her a message يترك لها رسالة."},
{"tag":"U6_V","qNum":13,"question":"13 Find 'Sylvie' on the phone and ___ the button.","options":["A press","B call","C answer","D ring"],"correct":0,"exp":"press the button يضغط الزر."},
{"tag":"U6_V","qNum":14,"question":"14 Can you finish your ___?","options":["A call","B message","C answer","D ring"],"correct":0,"exp":"finish your call ينهي مكالمتك."},
{"tag":"U6_V","qNum":15,"question":"15 L___ is a popular kind of music from South America.","options":["A Latin","B Lating","C Latine","D Latino"],"correct":0,"exp":"Latin موسيقى لاتينية."},
{"tag":"U6_V","qNum":16,"question":"16 My brother plays the guitar in a heavy ___ band.","options":["A metal","B medal","C mettle","D mental"],"correct":0,"exp":"heavy metal نوع موسيقى."},
{"tag":"U6_V","qNum":17,"question":"17 I like R & B, but I don't like hip ___.","options":["A hop","B hope","C hip","D hoper"],"correct":0,"exp":"hip hop نوع موسيقى."},
{"tag":"U6_V","qNum":18,"question":"18 We often go to classical music ___.","options":["A concerts","B concert","C concers","D concet"],"correct":0,"exp":"classical music concerts حفلات موسيقى كلاسيكية."},
{"tag":"U6_V","qNum":19,"question":"19 Louis Armstrong is my favorite ___ musician.","options":["A jazz","B jaz","C jass","D juzz"],"correct":0,"exp":"jazz موسيقى الجاز."},
{"tag":"U6_V","qNum":20,"question":"20 Ben plays the viola in an ___.","options":["A orchestra","B orchesta","C orcestra","D orchastra"],"correct":0,"exp":"orchestra أوركسترا."}

],
listening: {
A: [
    
  {"qNum": 1, "tag": "P1", "partName": "Part 1 - Daily Life (نموذج A) - File4", "audioSrc": audioPart1_5, "speaker": "1", "startTime": 4, "endTime": 30, "question": "1. Where does Kelly usually have breakfast?", "options": ["A) in a café", "B) at work", "C) at home", "D) on the train"], "correct": 1},
  {"qNum": 2, "tag": "P1", "partName": "Part 1 - Daily Life (نموذج A) - File4", "audioSrc": audioPart1_5, "speaker": "2", "startTime": 31, "endTime": 53, "question": "2. What does Pete do when he arrives home?", "options": ["A) make dinner", "B) take a shower", "C) read a book", "D) go shopping"], "correct": 1},
  {"qNum": 3, "tag": "P1", "partName": "Part 1 - Daily Life (نموذج A) - File4", "audioSrc": audioPart1_5, "speaker": "3", "startTime": 54, "endTime": 80, "question": "3. How often does John's parents see their son?", "options": ["A) every four weeks", "B) three times a year", "C) once a week", "D) every day"], "correct": 1},
  {"qNum": 4, "tag": "P1", "partName": "Part 1 - Daily Life (نموذج A) - File4", "audioSrc": audioPart1_5, "speaker": "4", "startTime": 81, "endTime": 109, "question": "4. What does Jill do on Saturday afternoon?", "options": ["A) go to the movies", "B) go shopping", "C) meet her boyfriend", "D) go out with her friends"], "correct": 1},
  {"qNum": 5, "tag": "P1", "partName": "Part 1 - Daily Life (نموذج A) - File4", "audioSrc": audioPart1_5, "speaker": "5", "startTime": 110, "endTime": 144, "question": "5. What time does Phil usually get up on Saturdays?", "options": ["A) 8 a.m.", "B) 6 a.m.", "C) 9 a.m.", "D) 7 a.m."], "correct": 2},
  {"qNum": 6, "tag": "P2", "partName": "Part 2 - Weather (نموذج A) - File5", "audioSrc": audioPart2_5, "speaker": "6", "startTime": 4, "endTime": 22, "question": "6. Conversation 1: Which statement is true?", "options": ["A) It's summer in the US.", "B) It's summer in Australia.", "C) It's winter in Australia.", "D) It's summer in both countries."], "correct": 1},
  {"qNum": 7, "tag": "P2", "partName": "Part 2 - Weather (نموذج A) - File5", "audioSrc": audioPart2_5, "speaker": "7", "startTime": 23, "endTime": 56, "question": "7. Conversation 2: What does Kay do when it's hot?", "options": ["A) Kay goes to the river with a book when it's hot.", "B) Kay relaxes on the beach when it's hot.", "C) Kay goes shopping when it's hot.", "D) Kay stays at home when it's hot."], "correct": 0},
  {"qNum": 8, "tag": "P2", "partName": "Part 2 - Weather (نموذج A) - File5", "audioSrc": audioPart2_5, "speaker": "8", "startTime": 57, "endTime": 77, "question": "8. Conversation 3: What's the weather like in New England?", "options": ["A) It's raining in New England.", "B) It's not very warm in New England.", "C) It's snowing in New England.", "D) It's very hot in New England."], "correct": 1},
  {"qNum": 9, "tag": "P2", "partName": "Part 2 - Weather (نموذج A) - File5", "audioSrc": audioPart2_5, "speaker": "9", "startTime": 78, "endTime": 100, "question": "9. Conversation 4: What is the problem on the road?", "options": ["A) There is sometimes ice on the road.", "B) It's sometimes difficult to see the road.", "C) There is a lot of traffic.", "D) The road is closed."], "correct": 1},
  {"qNum": 10, "tag": "P2", "partName": "Part 2 - Weather (نموذج A) - File5", "audioSrc": audioPart2_5, "speaker": "10", "startTime": 101, "endTime": 132, "question": "10. Conversation 5: What does Dave prefer?", "options": ["A) Dave prefers cold weather.", "B) Dave prefers hot weather.", "C) He likes summer the most.", "D) He doesn't like any season."], "correct": 0},
  {"qNum": 11, "tag": "P3", "partName": "Part 3 - Phone Calls (نموذج A) - File6", "audioSrc": audioPart3_5, "speaker": "11", "startTime": 4, "endTime": 30, "question": "11. Conversation 1: What does Kate do?", "options": ["A) uses another person's phone to call his / her friend.", "B) leaves a message for his / her cousin.", "C) has a new phone.", "D) is calling a colleague."], "correct": 1},
  {"qNum": 12, "tag": "P3", "partName": "Part 3 - Phone Calls (نموذج A) - File6", "audioSrc": audioPart3_5, "speaker": "12", "startTime": 31, "endTime": 59, "question": "12. Conversation 2: What does Pete do?", "options": ["A) leaves a message for his / her cousin.", "B) uses another person's phone to call his / her friend.", "C) doesn't call the correct number.", "D) is calling a colleague."], "correct": 1},
  {"qNum": 13, "tag": "P3", "partName": "Part 3 - Phone Calls (نموذج A) - File6", "audioSrc": audioPart3_5, "speaker": "13", "startTime": 60, "endTime": 85, "question": "13. Conversation 3: What does Bill do?", "options": ["A) has a new phone.", "B) is calling a colleague.", "C) doesn't call the correct number.", "D) leaves a message for his / her cousin."], "correct": 2},
  {"qNum": 14, "tag": "P3", "partName": "Part 3 - Phone Calls (نموذج A) - File6", "audioSrc": audioPart3_5, "speaker": "14", "startTime": 85, "endTime": 106, "question": "14. Conversation 4: What does Anna do?", "options": ["A) is calling a colleague.", "B) has a new phone.", "C) uses another person's phone to call his / her friend.", "D) leaves a message for his / her cousin."], "correct": 0},
  {"qNum": 15, "tag": "P3", "partName": "Part 3 - Phone Calls (نموذج A) - File6", "audioSrc": audioPart3_5, "speaker": "15", "startTime": 107, "endTime": 138, "question": "15. Conversation 5: What does Sally do?", "options": ["A) doesn't call the correct number.", "B) leaves a message for his / her cousin.", "C) has a new phone.", "D) is calling a colleague."], "correct": 2}

],


}};

